tasks:
  test P2R:
    mock:
      - { title: 'Name.Of.The.Series.S01E01.XviD-FlexGet', series_name: 'Name Of The Series', series_season: 1, series_episode: 1 }
    post2rest:
      url: 'http://localhost:5984/rensub'
      data:
        subtitle: yes
    accept_all: yes